name: Deploy to GitHub Pages

on:
  workflow_call:

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          # cache: npm

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Create .env config file
        run: cp example.env .env

      - name: Build website
        run: npm run build && cp -r build app

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: app

  deploy:
    name: Deploy via SSH
    needs: build
    if: ${{ github.ref_name == github.event.repository.default_branch }}

    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-folder
          path: app

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SECRET_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H marco-lenschau.de >> ~/.ssh/known_hosts

      - name: Deploy via SCP
        run: |
          scp -r app/* github@marco-lenschau.de:/var/www/html/docs/